version: "3.9"

services:
  queue:
    image: softwaremill/elasticmq:latest
    container_name: sns_sqs_elacticmq
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - ./config/elasticmq.conf:/opt/elasticmq.conf

  vertica:
    platform: linux/amd64
    environment:
      APP_DB_USER: "newdbadmin"
      APP_DB_PASSWORD: "vertica"
      # TZ: "Europe/Prague"
      VERTICA_MEMDEBUG: 2
    container_name: vertica-ce
    image: vertica/vertica-ce
    ports:
      - "5433:5433"
      - "5444:5444"
    deploy:
      mode: global
    volumes:
      - type: volume
        source: vertica-data
        target: /data
volumes:
  vertica-data: